title:            Gene's DevBlog
description:      The blog wherein my misadventures in software development are documented for your displeasure.
comments:         true
disqus_shortname: gene5ive
reading_time:     true
words_per_minute: 200
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
url: https://gene5ive.github.io/

# Owner/author information
owner:
  name:           Gene Johnson
  avatar:         avatar.jpg
  bio:            "I am a self-taught developer, artist, writer, and general dabbler in all things fascinating. This blog attempts to capture all and only those development experiences which may be described as interesting or useful."
  email:          jedigene@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        gene5ive
  facebook:       gene5ive
  github:         gene5ive
  stackexchange:  stackexchange.com/users/2712542/gene-johnson
  linkedin:       frankeugenejohnson
  instagram:      gene5ive
  flickr:
  tumblr:         cabellero
  # google plus id, include the '+', eg +mmistakes
  google_plus:    +GeneJohnson

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Los_Angeles
future:      true
highlighter: pygments
markdown:    kramdown
gems:
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Default settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: Gene Johnson
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Amount of post to show on home page
paginate: 5

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
